### ISSUE TITLE
Atom numbering in example formula

### ISSUE THREAD

**Issue by jaanos** [VidStarc/LVR-projekt#1]
The example formula `example1.txt` specifies that there are 100 atoms, however, an atom `350` appears in several clauses.

Please check that your formula is as intended, and ensure that the highest numbered atom does not exceed the specified number of atoms. One easy way to fix this would be to replace `350` with `101`, and specify in the first line that there are 101 atoms.

**Comment by VidStarc** [comment]
ok now it is ok

**Comment by jaanos** [comment]
Your file now lacks the first line specifying the number of atoms and clauses.

**Comment by VidStarc** [comment]
right, i add it.

**Comment by jaanos** [comment]
OK, thanks, I've updated the link to your latest commit.
